[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
framework = { path = "../framework" }
ahash = "0.8.11"
rustpython = { version = "0.3.1", features = ["rustpython-stdlib", "ssl", "default", "importlib"] }
rustpython-vm = "0.3.1"
